# Generated by Django 3.0.6 on 2020-06-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0002_auto_20200616_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='photo',
            field=models.ImageField(default='photos/def.png', upload_to='photos'),
        ),
    ]
