# Generated by Django 3.0.6 on 2020-06-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0003_auto_20200616_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
