# Generated by Django 3.0.6 on 2020-06-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0004_tour_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='client',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
