# Generated by Django 3.0.7 on 2020-07-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0008_auto_20200712_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='confirmed_reservations',
            field=models.IntegerField(default=0),
        ),
    ]
