# Generated by Django 3.0.7 on 2020-07-16 18:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0009_tour_confirmed_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reservation_code',
            field=models.CharField(default=uuid.UUID('6bb3a4ce-f67c-47a5-b59c-1df28f246730'), max_length=50),
        ),
    ]
