# Generated by Django 3.0.7 on 2020-07-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0010_client_reservation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='reservation_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
